version: 2

builds:
  - ldflags:
      - -s -w -X github.com/moonwalker/comet/internal/version.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
